export const TYPES = {
    ADD_SELECTED_PRODUCT: 'ADD_SELECTED_PRODUCT',
    ADD_QUANTITY: 'ADD_QUANTITY',
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT'
}